# Generated by Django 4.1 on 2022-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=2000)),
                ('venue', models.CharField(max_length=2000)),
                ('support_phone', models.CharField(max_length=2000)),
                ('support_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
