# Generated by Django 4.1 on 2022-09-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='church',
            table='Church',
        ),
    ]
