# Generated by Django 4.1 on 2022-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('theme', models.CharField(max_length=2000)),
                ('content1', models.CharField(max_length=200000)),
                ('content2', models.CharField(max_length=200000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('map_code', models.CharField(max_length=2000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('sermons_theme', models.CharField(max_length=2000)),
                ('sermon_location', models.CharField(max_length=2000)),
            ],
        ),
    ]
