# Generated by Django 4.1 on 2022-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio', models.CharField(max_length=2000)),
                ('article', models.CharField(max_length=2000)),
                ('audio_duration', models.CharField(max_length=2000)),
                ('Icon', models.CharField(choices=[('heart', 'heart'), ('heart', 'heart'), ('heart', 'heart')], max_length=2000)),
            ],
        ),
    ]
